# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DBIWC <- function(sam, k, max_itr = 20L, tol = 1e-4) {
    .Call(`_mixedCluster_DBIWC`, sam, k, max_itr, tol)
}

SAWC <- function(sam, k, max_itr = 20L, tol = 1e-4) {
    .Call(`_mixedCluster_SAWC`, sam, k, max_itr, tol)
}

